services:
  test_db:
    container_name: "api-currency-converter-test"
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASS}
      POSTGRES_DB: ${TEST_DB_NAME}
    ports:
      - "${TEST_DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U POSTGRES_USER -d POSTGRES_PASSWORD"]
      interval: 1m30s
      timeout: 30s
      retries: 5
    networks:
      - custom

networks:
  custom:
    driver: bridge
